Board impl
cmput402-w19/assignment4tdd-goodteam pull request #7
Opened 2019-02-22 22:54 UTC by knewbury01

This corresponds to the following issues:

[Piece impl](https://github.com/cmput402-w19/assignment4tdd-goodteam/issues/4)
[Square impl](https://github.com/cmput402-w19/assignment4tdd-goodteam/issues/5)
[Board impl](https://github.com/cmput402-w19/assignment4tdd-goodteam/issues/6)

2019-02-22 23:29 UTC, kuzi117 commented
What coverage is missing here?

2019-02-22 23:40 UTC, kuzi117 requested changes
This might seem like a lot, it's mostly just me taking issue with one thing, using strings to pass around enum states. Enums are meant to mean that "one thing that is this". If you need to attach extra data you can make the enum have fields.

2019-02-22 23:40 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +	masterStatus = master;
Is the "king" called the master?

2019-02-22 23:40 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Board.java
> +	for (int i = 0; i < size; i++){
This loop might be better created using two loops, one for each color. That way you can just iterate once over size (horizontally) and know that one loop is for the top row (color 1) and the next loop is the bottom row (color 2).

2019-02-22 23:40 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +	team = color;
I'd rather switch color to be team and then do `this.team = team` because I'm going to need the name "color" for the actual color to render.

2019-02-22 23:40 UTC, kuzi117 commented on src/test/java/BoardTest.java
> +	assert (board.getCurrentPlayer().toString().equals("RED"));
Shouldn't this be `getCurrentPlayer.equals(Player.RED)`? Why check string equality when we have enum equality?

2019-02-22 23:40 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Square.java
> +    public String getState(){
This seems strange to pass around strings here. Should just be returning State.

2019-02-22 23:40 UTC, kuzi117 commented on src/test/java/BoardTest.java
> +		assert (board.getSquareAtPos(i, j).getState().equals("OCCUPIED"));
These will need to change to enum equality when Square.getState changes.

2019-02-22 23:40 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +    private String team;
This should be using an enum, probably Board.Player.

2019-02-22 23:44 UTC, kuzi117 commented
In particular, I wrote something like this for team in the Renderer. I'm realising that it should actually be extracted to board but you should leave out some elements like color and I'll add them when I need them:
```java
    private enum Team {
        RED(0, Color.RED),
        BLACK(1, Color.BLACK);

        // Team properties.
        public final int idx;
        public final Color color;

        Team(int idx, Color color) {
            this.idx = idx;
            this.color = color;
        }
    }```

Change it as you see fit (probably drop idx and color and add your own fields). If you need a string from any of this checkout enum.name() (final, can't be overridden) or enum.toString() (overrideable).

2019-02-23 02:41 UTC, knewbury01 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Board.java
> +	for (int i = 0; i < size; i++){
I wrote it as two loops, but one for mid board to be empty and one for first and last row which only iterates over j and inits both first and last row at same time,
I think this is clearer, please confirm

2019-02-23 02:41 UTC, knewbury01 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +	team = color;
done@

2019-02-23 02:42 UTC, knewbury01 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Square.java
> +    public String getState(){
Done!

2019-02-23 02:42 UTC, knewbury01 commented on src/test/java/BoardTest.java
> +		assert (board.getSquareAtPos(i, j).getState().equals("OCCUPIED"));
Done!

2019-02-23 02:42 UTC, knewbury01 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +    private String team;
done! except its Board.Team but same thing

2019-02-23 02:45 UTC, knewbury01 commented on src/test/java/BoardTest.java
> +	assert (board.getCurrentPlayer().toString().equals("RED"));
Done!

2019-02-23 03:20 UTC, kuzi117 reviewed
Just some final quick changes.

2019-02-23 03:20 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Board.java
> +	    Square squareFirstRow = new Square();
I _do_ think this is more clear, thank you. The one thing is, you shouldn't need to create and set a new Square here. You've already filled it it, I think you can just modify the square that's already there.

2019-02-23 03:20 UTC, kuzi117 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +	masterStatus = master;
Would prefer this named as `isMaster` like its accessor function  (being picky, not necssary).

2019-02-23 03:38 UTC, knewbury01 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Piece.java
> +	masterStatus = master;
Agree!

2019-02-23 03:39 UTC, knewbury01 commented on src/main/java/cs/ualberta/cmput402/boardgame/board/Board.java
> +	    Square squareFirstRow = new Square();
Agree! Didnt actually place all squares at first, but this leads to ... why not! that makes more sense!

2019-02-23 03:45 UTC, kuzi117 approved these changes
Looks good, thanks for bearing with me!

2019-02-23 05:44 UTC, merged